### ISSUE TITLE
FR! .asPmono, asPmonoArtic

### ISSUE THREAD

**Issue by cdbzb** [shimpe/panola#1]
Great Quark - thanks!

Please add methods to support Pmono and PmonoArtic! - otherwise we can;t use custom keys in those situations! thanks

**Comment by cdbzb** [comment]
Ahhh just found .customPropertyPattern("xxx") - that is a workaround for now!

**Comment by shimpe** [comment]
Excellent suggestion though, I'll look into it.

**Comment by shimpe** [comment]
This implemented in the latest version now.
