### ISSUE TITLE
[question] how to handle rests?

### ISSUE THREAD

**Issue by grammoboy2** [shimpe/panola#4]
I'm pretty new to supercollider, but I was wondering how one handles rests when working with panola?

**Comment by shimpe** [comment]
Hi, you can use the notename "r" for a rest.
So e.g. r_2 is half rest or r_4 is a quarter rest.

**Comment by grammoboy2** [comment]
Thanks. 
Another question is how to sync it with other pbindefs that doesn't use panola. The panola examples seems to ignore the TempoClock, so how to sync and quant them? 

Normally I use Pbindef(\synth).play(t)
Where t is the TempoClock.

(
Pbindef(
...
).quant_(4)
)

**Comment by shimpe** [comment]
First, a warning: tempo in Panola is one of the areas I'm not really proud of. 
I really ought to revise the specification and implementation of tempo related stuff.

Having said that, there are two possibilities:

1.  Tempo can be specified in the panola string itself with e.g. 
```
~phrase = Panola.new("c@tempo[180] d e f g");
```

2. or, much more flexibly, you can build your own Pbind and extract from Panola only what you need, e.g: 
```
~phrase = Panola.new("c d e f g");
~pattern = Pbind(
    \instrument, \default
    \midinote, ~phrase.midinotePattern,
    \amp, ~phrase.volumePattern,
    \dur, ~phrase.durationPattern,
    \legato, ~phrase.pdurPattern,
    \lag, ~phrase.lagPattern,
); 
```

at this point you have a normal Pbind which you can play on a TempoClock like any other Pbind.

**Comment by grammoboy2** [comment]
Nice, the second option is what I'm looking for. Is it also possible to repeat it infinitely (inf)?

Pseq([~phrase.midinotePattern], inf), 

doesn't seems to work

**Comment by grammoboy2** [comment]
It does work actually, sorry.

**Comment by shimpe** [comment]
To repeat patterns, it's even shorter to use Pn(~phrase.midinotePattern, inf)
